# NumPy

## memory consumption comparison between list & Numpy array

In [5]:
# importing numpy package
import numpy as np

# importing system module
import sys

# declaring a list of 1000 elements
S= range(1000)

# printing size of each element of the list
print("Size of each element of list in bytes: ",sys.getsizeof(S))

# printing size of the whole list
print("Size of the whole list in bytes: ",sys.getsizeof(S)*len(S))

# declaring a Numpy array of 1000 elements
D= np.arange(1000)

# printing size of each element of the Numpy array
print("Size of each element of the Numpy array in bytes: ",D.itemsize)

# printing size of the whole Numpy array
print("Size of the whole Numpy array in bytes: ",D.size*D.itemsize)

Size of each element of list in bytes:  48
Size of the whole list in bytes:  48000
Size of each element of the Numpy array in bytes:  8
Size of the whole Numpy array in bytes:  8000


## Time comparison between list & Numpy array

In [6]:
# importing required packages
import numpy
import time

# size of arrays and lists
size = 1000000

# declaring lists
list1 = range(size)
list2 = range(size)

# declaring arrays
array1 = numpy.arange(size)
array2 = numpy.arange(size)

# capturing time before the multiplication of Python lists
initialTime = time.time()

# multiplying elements of both the lists and stored in another list
resultantList = [(a * b) for a, b in zip(list1, list2)]

# calculating execution time
print("Time taken by Lists to perform multiplication:",
    (time.time() - initialTime),
    "seconds")

# capturing time before the multiplication of Numpy arrays
initialTime = time.time()

# multiplying elements of both the Numpy arrays and stored in another Numpy array
resultantArray = array1 * array2

# calculating execution time
print("Time taken by NumPy Arrays to perform multiplication:",
    (time.time() - initialTime),
    "seconds")

Time taken by Lists to perform multiplication: 0.07015061378479004 seconds
Time taken by NumPy Arrays to perform multiplication: 0.0012545585632324219 seconds


## Basic Comparison between Numpy and List

In [1]:
number = [1, 2, 3, 4]
print(number + 2)

TypeError: can only concatenate list (not "int") to list

In [2]:
import numpy as np
number = np.array([1, 2, 3, 4])
print(number + 2)

[3 4 5 6]


In [3]:
a = [1, 2, 3]
b = [4, 5, 6]
print(a + b)

[1, 2, 3, 4, 5, 6]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


## Create NumPy array

In [8]:
y = np.array([])
print(y)

[]


In [7]:
import numpy as np

x = np.empty([3,2], dtype = int)
print(x)

[[    1462588473393     1462908606752]
 [    1462588488752 19703656396554240]
 [    1462687114912  2251799813685330]]


In [11]:
import numpy as np

# set as float type
x = np.zeros(5)
y = np.zeros(5, dtype = int)
#x = np.zeros((5, ), dtype = int)
print(x)
print(y)

[0. 0. 0. 0. 0.]
[0 0 0 0 0]


In [49]:
import numpy as np

# set float type
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [51]:
# set 3-Dimensional array
x = np.zeros([3,2,2], dtype = int)
print(x)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [16]:
print(x.ndim, x.shape, x.size)

3 (3, 2, 2) 12


In [17]:
import numpy as np
 
x = np.arange(5)  
print (x)

[0 1 2 3 4]


In [18]:
import numpy as np
 
x = np.arange(5, dtype = float)  
print (x)

[0. 1. 2. 3. 4.]


In [19]:
import numpy as np

x = np.arange(10,20,2)  # Set the starting point and end point, with step length
print (x)

[10 12 14 16 18]


In [20]:
import numpy as np

a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [21]:
import numpy as np
 
a = np.linspace(10, 20,  5, endpoint =  False)  
print(a)

[10. 12. 14. 16. 18.]


In [22]:
import numpy as np

a =np.linspace(1,10,10,retstep= True, dtype = 'int') # If True, also returns the spacing between values
 
print(a)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), np.float64(1.0))


## Numpy Reshape

In [24]:
import numpy as np

a = np.arange(8)
print(a)

b = a.reshape(4, 2)
print(b)

[0 1 2 3 4 5 6 7]
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [25]:
c = b.reshape(2, 4, order = 'F')
print(c)

[[0 4 1 5]
 [2 6 3 7]]


## NumPy Resize

In [26]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])

print(a)

b = np.resize(a, (3, 2))
print(b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [27]:
c = np.resize(a, (3,3))
print(c)

[[1 2 3]
 [4 5 6]
 [1 2 3]]


In [28]:
d = np.resize(a, (2, 2))
print(d)

[[1 2]
 [3 4]]


## Rounding with NumPy

In [33]:
import numpy as np

a = np.array([1.0, 5.55, 123, 0.567, 25.532])

print(np.around(a, decimals = 1))

[  1.    5.6 123.    0.6  25.5]


In [35]:
import numpy as np

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])

print(np.floor(a))

[-2.  1. -1.  0. 10.]


In [37]:
import numpy as np

a = np.array([-1.7, 1.5, -0.2, 0.6, 10])

print(np.ceil(a))

[-1.  2. -0.  1. 10.]


## NumPy Arithmetic

In [42]:
import numpy as np

a = np.arange(9).reshape(3, 3)

print(a)

b = np.array([10, 10, 11])
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[10 10 11]


In [44]:
print(np.add(a, b))

[[10 11 13]
 [13 14 16]
 [16 17 19]]


In [45]:
print(np.subtract(a, b))

[[-10  -9  -9]
 [ -7  -6  -6]
 [ -4  -3  -3]]


In [46]:
print(np.multiply(a, b))

[[ 0 10 22]
 [30 40 55]
 [60 70 88]]


In [47]:
print(np.divide(a, b))

[[0.         0.1        0.18181818]
 [0.3        0.4        0.45454545]
 [0.6        0.7        0.72727273]]


In [48]:
a = np.array([10, 100, 1000])
print(np.power(a, 2))

b = np.array([1, 2, 3])
print(np.power(a, b))

[    100   10000 1000000]
[        10      10000 1000000000]
